### ISSUE TITLE
contactの下線がずれている

### ISSUE THREAD

**Issue by okutani-t** [okutani-t/team-clap-corp#20]
## 内容

![image](https://user-images.githubusercontent.com/14942798/38578887-36bddcfe-3d40-11e8-897a-12efd318b847.png)

## コメント

transformあたりを使ってあげるとよいかも？

**Comment by Nobu-Ku** [comment]
修正しました！ここから修正すれば良かったんですかね。。。
新しくプルリク作っちゃいました・・・
https://github.com/okutani-t/team-clap-corp/pull/21
